In [ ]:
import numpy as np  #shift plus enter to run

In [3]:
data = [6,7.5,8,0,1]

In [4]:
arr1= np.array(data)

In [5]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr2.dtype

dtype('int32')

In [12]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [13]:
arr1.dtype

dtype('float64')

In [14]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Operations

In [17]:
arr = np.array([1.,2.,3.],[4.,5.,6.])

TypeError: data type not understood

In [18]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [19]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [20]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [21]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [23]:
arr**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

# indexing and slicing

In [24]:
arr = np.arange(10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[5]

5

In [27]:
arr[5:8]

array([5, 6, 7])

In [28]:
arr[5:8]= 12

In [29]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [30]:
arr_slice= arr[5:8]

In [31]:
arr_slice[1] = 12345

In [32]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [33]:
arr_slice

array([   12, 12345,    12])

In [34]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [35]:
arr_slice[:] = 64

In [36]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [37]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr2d{[2]

SyntaxError: invalid syntax (<ipython-input-39-04c51f278083>, line 1)

In [40]:
arr2d[2]

array([7, 8, 9])

arr2d[0][2]

In [41]:
arr2d[0][2]

3

In [42]:
arr2d[0,2]

3

In [43]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [44]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
old_values = arr3d[0].copy()

In [46]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr3d[0] = 42

In [48]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d = old_values

In [50]:
arr3d

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [53]:
arr[:2]

array([0, 1])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [58]:
arr2d[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])