In [3]:
import numpy as np
data1 = [2,3,4.5,6]

In [4]:
arr1 = np.array(data1)

In [6]:
arr1

array([ 2. ,  3. ,  4.5,  6. ])

In [7]:
arr_split = data1[2:4]

In [8]:
arr_split

[4.5, 6]

In [9]:
arr_split[1]

6

In [10]:
arr2 = np.empty((8,4))

In [11]:
arr2

array([[  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          5.35598855e-312],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          5.35598855e-312],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          5.35598855e-312],
       [  0.00000000e+000,   5.35598855e-312,   0.00000000e+000,
          5.35598855e-312],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          5.35598855e-312],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          5.35598855e-312],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000]])

In [15]:
for i in range(8):
    arr2[i] = i

In [16]:
arr2

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [17]:
arr3 = np.arange(32)

In [18]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [20]:
arr3 = np.arange(32).reshape(4,8)

In [21]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [22]:
from pandas import Series, DataFrame

In [23]:
import pandas as pd

In [24]:
obj = [1,2,3,4]

In [25]:
obj

[1, 2, 3, 4]

In [26]:
obj.values

AttributeError: 'list' object has no attribute 'values'

In [27]:
obj = Series([1,2,3,4])

In [28]:
obj.values

array([1, 2, 3, 4], dtype=int64)

In [29]:
obj2 = [5,6,7,8]

In [30]:
obj2.values

AttributeError: 'list' object has no attribute 'values'

In [31]:
obj2.index

<function list.index>

In [32]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [33]:
obj2.ndmin

AttributeError: 'list' object has no attribute 'ndmin'

In [34]:
obj2 = np.array(obj2)

In [35]:
obj2.ndim

1

In [36]:
obj2.shape

(4,)

In [37]:
obj.index

RangeIndex(start=0, stop=4, step=1)